version: "3.9"

networks:
  reverse-proxy:
    external: true

services:
  ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.8.6
    ports:
      - 8000:8000
    volumes:
      - /mnt/user/docker/volumes/paperless:/usr/src/paperless/data
      - /mnt/user/vault/documents:/usr/src/paperless/media
      - /mnt/user/vault/exports:/usr/src/paperless/export
      - /mnt/user/scan:/usr/src/paperless/consume
    environment:
      USERMAP_UID: 99
      USERMAP_GID: 100
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
      ## Cache
      PAPERLESS_REDIS: redis://unraid.lan:6379
      PAPERLESS_REDIS_PREFIX: paperless
      ## Database
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBHOST: unraid.lan #e.g. 192.168.2.2
      PAPERLESS_DBPORT: ${POSTGRES_PORT}
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: ${POSTGRES_USER}
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD}
    networks:
      - reverse-proxy
    deploy:
      labels:
        ## Proxy
        - traefik.enable=true
        - traefik.http.routers.paperless.rule=Host(`paperless.lan`)
        - traefik.http.routers.paperless.entrypoints=websecure
        - traefik.http.routers.paperless.service=paperless
        - traefik.http.routers.paperless.tls=true
        - traefik.http.services.paperless.loadbalancer.server.port=8000
        - traefik.http.routers.paperless.middlewares=middlewares-authentik@file
        ## Homepage
          #Service
        - homepage.group=Productivity
        - homepage.name=Paperless
        - homepage.description=Document management
        - homepage.icon=paperlessngx.png
        - homepage.server=my-docker
        - homepage.container=paperless_ngx
        - homepage.href=http://192.168.2.3:8000
          #Widget
        - homepage.widget.type=paperlessngx
        - homepage.widget.url=http://192.168.2.3:8000
        - homepage.widget.username=${PAPERLESS_ADMIN_USER}
        - homepage.widget.password=${PAPERLESS_ADMIN_PASSWORD}
