name: 'paperless'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    env:
      PAPERLESS_ADMIN_USER: ${{ vars.PAPERLESS_ADMIN_USER }}
      PAPERLESS_ADMIN_PASSWORD: ${{ secrets.PAPERLESS_ADMIN_PASSWORD }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
      POSTGRES_PASS: ${{ secretsPOSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a container command
        run: |
          docker stack deploy -c paperless-ngx.yaml paperless
